name: 'Ageo_solutions'
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  get: ^4.6.6
  http: ^1.2.2
  flutter_svg: ^2.0.10+1
  calendar_date_picker2: ^1.0.2
  flutter_localizations:
    sdk: flutter
  retry: ^3.1.2
  flutter_secure_storage: ^9.0.0
  syncfusion_flutter_charts: ^26.1.40
  omni_datetime_picker: ^2.0.3
  web_socket_channel: ^3.0.0
  persistent_bottom_nav_bar_v2: ^5.3.0
  provider: ^6.1.2
  flutter_localization: ^0.2.1
  shared_preferences: ^2.3.0
 
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
flutter_icons: 
  android: true
  ios: true
  image_path: 'assets/images/360_F_375677469_UzQt3JpGywuXxkOlCkG7SJXXbiGsampv.jpg'
  adaptive_icon_background: '#ffffff'

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/logo.png
    - assets/icons/
